version: '3.7'

x-db-variables: 
  &db-variables
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_NAME: ${DB_NAME}
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_TYPE: ${DB_TYPE}

services:

######################
# postgres container
######################
  postgres:
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    image: postgres:10-alpine
    ports:
      - 5432:5432
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data

######################
# redis container
######################
  redis:
    container_name: ${CACHE_HOST}
    image: redis:5-alpine
    volumes:
      - cachedata:/data

######################
# server container
######################
  server:
    build: ./server
    depends_on:
      - postgres
      - redis
    environment:
      << : *db-variables
      NODE_ENV: ${NODE_ENV}
      CACHE_HOST: ${CACHE_HOST}
      APP_SERVER_PORT: 5000
    ports:
      - 5000:5000
    volumes:
      - ./server/src:/app/src
      - ~/.aws:/root/.aws:ro

######################
# client container
######################
  client:
    build: ./client
    environment:
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
      - NODE_PATH=${NODE_PATH}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public

######################
# end services
######################

######################
# named volumes
######################
volumes:
  dbdata:
  cachedata: